name: Build and Test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

env:
  CFLAGS: "-O2 -g3 -Wall -Werror"

jobs:
  ci:
    permissions:
      contents: read
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang
          - gcc
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    name: "Build and Test (PHP ${{ matrix.php }}, CC: ${{ matrix.compiler }})"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up PHP
        uses: shivammathur/setup-php@20529878ed81ef8e78ddf08b480401e6101a850f # 2.35.3
        with:
          php-version: ${{ matrix.php }}
          tools: none

      - name: Build
        run: phpize && ./configure CC=${{ matrix.compiler }} --silent && make --silent

      - name: Run tests
        run: make test
        env:
          NO_INTERACTION: "1"
          REPORT_EXIT_STATUS: "1"

  ci2:
    permissions:
      contents: read
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    name: "Build and Test (PHP ${{ matrix.php }}, Zend extensions enabled)"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up PHP
        uses: shivammathur/setup-php@20529878ed81ef8e78ddf08b480401e6101a850f # 2.35.3
        with:
          php-version: ${{ matrix.php }}
          tools: none

      - name: Build and install
        run: phpize && ./configure --silent && make --silent && sudo make install

      - name: Enable the extension
        uses: shivammathur/setup-php@20529878ed81ef8e78ddf08b480401e6101a850f # 2.35.3
        with:
          php-version: ${{ matrix.php }}
          tools: none
          extensions: xdebug
          ini-values: extension=disableeval.so,"xdebug.mode=develop,trace,debug"

      - name: Smoke test
        run: php -m

      - name: Run tests
        run: php run-tests.php --show-diff -d 'error_reporting=24575'
        env:
          NO_INTERACTION: "1"
          REPORT_EXIT_STATUS: "1"
          TEST_PHP_EXECUTABLE: "/usr/bin/php"
