name: Build and Test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

env:
  CFLAGS: "-O2 -g3 -Wall -Werror"

jobs:
  ci:
    permissions:
      contents: read
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang
          - gcc
        php:
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
    name: "Build and Test (PHP ${{ matrix.php }}, CC: ${{ matrix.compiler }})"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Set up PHP
        uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d # 2.24.0
        with:
          php-version: ${{ matrix.php }}
          tools: none

      - name: Build
        run: phpize && ./configure CC=${{ matrix.compiler }} --silent && make --silent

      - name: Run tests
        run: make test
        env:
          NO_INTERACTION: "1"
          REPORT_EXIT_STATUS: "1"

  ci2:
    permissions:
      contents: read
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        php:
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
    name: "Build and Test (PHP ${{ matrix.php }}, Zend extensions enabled"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Set up PHP
        uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d # 2.24.0
        with:
          php-version: ${{ matrix.php }}
          tools: none

      - name: Build and install
        run: phpize && ./configure --silent && make --silent && sudo make install

      - name: Enable the extension
        uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d # 2.24.0
        with:
          php-version: ${{ matrix.php }}
          tools: none
          extensions: xdebug
          ini-values: extension=disableeval.so,"xdebug.mode=develop,trace,debug"

      - name: Smoke test
        run: php -m

      - name: Run tests
        run: php run-tests.php --show-diff -d 'error_reporting=24575'
        env:
          NO_INTERACTION: "1"
          REPORT_EXIT_STATUS: "1"
          TEST_PHP_EXECUTABLE: "/usr/bin/php"
